### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by Chaoschicken** [StormyMode/TheScientistsToolbox#2]
I know this is not your pack's issue but I am playing on the test server and the golden shovel is not making claims as usual. After I place chest and get initial claim the golden shovel is not allowing me to expand it as it should.

**Comment by StormyMode** [comment]
There is a bug in the server-side claims Plugin. There is a quick-fix
Plugin available, but unfortunately I'm not the server owner and he won't
install it.

A temporary work around is to right click an air block in the direction you
want to claim. Suddenly it works, but only when Right-Clicked at nothing
(air).
