### ISSUE TITLE
Transmutation table

### ISSUE THREAD

**Issue by Chaoschicken** [StormyMode/TheScientistsToolbox#3]
Partially removed?  Searchable but no image or recipe. Is this on purpose? If so how can I add back just for private server?

**Comment by StormyMode** [comment]
Equivilent Exchange 3 is in heavy Alpha development. There are not many
features. Although in the next Toolbox Update: EE3 will update from version
#436 to version #456. In the changelogs it states about tons of Fixes and
features. So enjoy the future Toolbox coming Soon!

[Just to Clarify: Toolbox didn't disable anything from EE3. EE3 simply
hasn't implemented them yet]

**Comment by Chaoschicken** [comment]
Alright thanks. If they dont progress on EE3 then you might look at Project E. It is a copy of EE2 for 1.7.10 and is working already.

**Comment by StormyMode** [comment]
I'm not adding Project-E. Sorry I'm really looking forward to the future versions of EE3! And I'm definitely sure it will be worth the wait.
